### ISSUE TITLE
NECB 2015 Rules: Service water heating

### ISSUE THREAD

**Issue by khaddad** [canmet-energy/btap_tasks#12]
Spec writer: Mike
Implementation in BTAP: Jeff
Tester: Mike

Table 6.2.2.1 contains information on efficiencies of service hot-water equipment. The current implementation of the NECB 2011 rules for SHW makes use of several assumptions used in the compliance rules of ASHRAE 90.1. During this task, a document describing the current implementation of the SHW compliance rules will be reviewed. The method will then be updated for NECB 2015 based on the information in Table 6.2.2.1.

Quality assurance tasks:
New unit test for SWH
All unit tests pass
All regression tests pass

**Comment by phylroy** [comment]
Done but Mike has GIT issues.

**Comment by padmassun** [comment]
[Diff_of_space_type_expected_results.xlsx](https://github.com/canmet-energy/btap_tasks/files/2058211/Diff_of_space_type_expected_results.xlsx)

`SHW Watt/Person (W/person)` values has been changed.
## NOTE
`SHW Fraction Schedule` for `NECB2015-Space   Function-Storage room < 5 m2-sch-[A,B,C,D,E,F,G,H,I,J]` has a value of 0 instead of a string like `NECB-*-Service Water Heating`

@khaddad What are your thoughts on this?

**Comment by jblake59** [comment]
Moved to issue #46 and closed.
