### ISSUE TITLE
NECB 2015 Rules: Window positioning

### ISSUE THREAD

**Issue by khaddad** [canmet-energy/btap_tasks#13]
According to this rule (8.4.4.5(5)) each window on each exterior wall will have a sill at 0.9 m above the floor with a height of 1.8 m. Then the width of the window will be chosen so that the required FDWR is met.

Quality assurance tasks:
New unit test
All unit tests pass.
All regression tests pass

**Comment by phylroy** [comment]
I think there is a measure in the BCL that does just this, it may be useful to have a look and reuse that code.

**Comment by ckirney** [comment]
If NECB rules cause a geometry conflict,will contradict NECB as long as total building window to wall ration withing 10% of NECB.  If exceed this amount then will generate an error and provide the user with the offending window information.

**Comment by phylroy** [comment]
Iain Macdonald: Suggested to park this.

**Comment by ckirney** [comment]
Was going to implement NECB2015 8.4.4.5.(5) by a window centered on each exterior vertical surface of a model which (at least) partially encloses a conditioned space.  The window would be placed 0.9 m above the floor, be 1.8 m tall, and its width would be set so that the FDWR of the surface would match the maximum allowable FDWR.  Note that NECB does not say if only surfaces adjacent to conditioned spaces should be included.  However, @mlubun said that the intention was for FDWR only to be applied to surfaces adjacent to conditioned spaces.

Got as far as determining the vertical surfaces adjacent to conditioned spaces and removing sub surfaces from those surfaces (see surface_replace_existing_subsurfaces_with_centered_subsurface and find_exposed_conditioned_vertical_surfaces methods in Standards.Surface.rb).  What was left was determining the corners of the window, determining if the window would fit in the surface, and then creating the window (subsurface) in the surface.  This was would take a lot of time because of all of the geometry transformations required.  Openstudio has methods which can be used to help with this but they are all for 2D geometry (everything must be in the z plane).  So would have to take the surface, transform it to be on the z-plane, do all the fitting, geometry checking etc,, transform things back to where they started and then create the window.  This would take too long for now so am stopping here and moved on to other things.

**Comment by IainMacdonald** [comment]
Set priority to low
