### ISSUE TITLE
NECB 2017: Maximize FDWR and SRR by default

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#142]
### Description
This was brought up by Denis Bourgeois that the FDWR should be set to maximum to ensure that the reference is as poor as designer can make it.  This will involve creating an option in the create FDWR to either limit, or maximize the FDWR and / or the SRR.  This sentiment was echoed by Mike Lubun and Justin Pockar. 

### Approach
Currently the methods for [FDWR](https://github.com/NREL/openstudio-standards/blob/nrcan/lib/openstudio-standards/standards/necb/NECB2011/building_envelope.rb#L4) and for [SRR](https://github.com/NREL/openstudio-standards/blob/nrcan/lib/openstudio-standards/standards/necb/NECB2011/building_envelope.rb#L143) Set a limit to the ratios in the building.  They do not maximize.  So they use are very similar to the DOE reference locations and ratios where possible. 

It would be beneficial to keep the existing resizing algorithms as an option and to default it to maximize.  So I am suggesting to allow for an argument to be added to both the above methods to switch between "MAXIMIZE" and "LIMIT"  and to default to MAXIMIZE
Example
```
def apply_standard_window_to_wall_ratio(model:, fdwr: 'MAXIMIZE')
```
and 
```
def apply_standard_skylight_to_roof_ratio(model:, ssr: 'MAXIMIZE')
```

And add these kwargs with the default values to the parent method calls up to [this call](https://github.com/NREL/openstudio-standards/blob/nrcan/lib/openstudio-standards/standards/necb/NECB2011/necb_2011.rb#L147).. and above if required.  Once this is done, add the logic to maximize the ratios in the model to ensure the ratio matches the NECB value. 

### Testing Plan
Modify [this](https://github.com/NREL/openstudio-standards/blob/nrcan/test/necb/test_necb_constructions_fdwr.rb) test to ensure that both arguments work work (LIMIT and MAX) given the test models created in the test.   

### Waiting On
Nothing!

### Repositories Possibly  Involved

https://github.com/canmet-energy/btap
https://github.com/NREL/openstudio-standards/tree/nrcan

### Branch Name created for task 
nrcan_142

### Select the Project Code you will be charging to 2018-2019

| Client 	|WSBE  	|Name   	|Manager   	
|----------	|---	|---	|---	
|PERD   |P-002518.001.03	|Building Archetype	|Phylroy Lopez

**Comment by IainMacdonald** [comment]
Not sure I fully follow this task. When the value is to 'maximised' are we talking up to the maximum allowed in the code (e.g. 2% for SSR in 2017)? Or is it some other arbitrary maximum value? 

On a side note the TG-BE group are under the impression that in Part 8 you already set the reference building at the maximum allowed (2% for SSR and degree day dependent for windows). Is this not the case (I'm yet to look up the code!); or can someone confirm what BTAP does?

**Comment by rd2Bourgeois** [comment]
My understanding is that the current BTAP/NECB implementation assumes a 90.1-like approach to fenestration: reference FWDR & SSR equal proposed FWDR & SSR, but only up to a maximum (e.g. 38% FWDR in Vancouver). If one assumes that all new buildings comply to NECBs following the prescriptive path (a silly assumption), then there's nothing fundamentally wrong with the current BTAP NECB implementation. On the other hand, if one were to instead assume a trend like Europe's EPBD (where all new buildings are required to be modelled/simulated to demonstrate compliance), then Part 8 compliance protocols would be better suited. In such cases, all reference buildings in e.g. Vancouver would need to have 38% FWDR. I believe that is why Phyl suggests implementing this as an option.

**Comment by ckirney** [comment]
Now include two new optional arguments for 'model_create_prototype_model' method.  These are:
fdwr_set and ssr_set.  If fdwr_set is passed with 'MAXIMIZE' then the fdwr for the model will be set to the maximum allowed by the NECB version you are using.  If fdwr_set is passed with anything else then the current behaviour is used (fdwr set to whatever it is in the original model, unless that exceeds the NECB limit).  The fdwr_set argument is defaulted to 'MAXIMIZE'.  The same happens for ssr_set.  Note that when fdwr_set or ssr_set are used then all existing outside wall subsurfaces or roof subsurfaces are removed and replaced with windows or skylights, respectively, that produce the maximum amount defined in the NECB version you are using.

The following alterations were made:

-necb_2011.rb:
Addition of new arguments to model_create_prototype model, changes to where 'apply_standard_window_to_wall_ratio' and 'apply_standard_skylight_to_roof_ratio' methods are called in 'model_apply_standard' method so that that code can properly determine if spaces are conditioned or not.

-building_envelope.rb in NECB2011:
Modified 'apply_standard_window_to_wall_ratio' and 'apply_standard_skylight_to_roof_ratio' methods to call new 'apply_max_fdwr' and 'apply_max_ssr' methods.  Added the new 'apply_max_fdwr' and 'apply_max_ssr' methods which manage apply the maximum NECB fdwr and srr to the model.

-Standards.Surface.rb in Standards
Modified 'find_exposed_conditioned_vertical_surfaces' to return vertical (between 89 and 91 deg. to horizontal) surfaces adjacent to conditioned (not inculuding plenum) spaces.  Returns the following hash:

    exp_surf_info = {
        "total_exp_wall_area_m2" => total_exp_area,
        "exp_plenum_wall_area_m2" => exp_plenum_area,
        "exp_nonplenum_wall_area_m2" => exp_nonplenum_area,
        "exp_plenum_walls" => plenum_surfaces,
        "exp_nonplenum_walls" => exposed_surfaces
    }

Added 'find_exposed_conditioned_roof_surfaces' method returns RoofCeiling' 'Outdoor' surfaces adjacent to conditioned spaces (not including plenums).  Returns the following hash:

    exp_surf_info = {
        "total_exp_roof_area_m2" => total_exp_area,
        "exp_plenum_roof_area_m2" => exp_plenum_area,
        "exp_nonplenum_roof_area_m2" => exp_nonplenum_area,
        "exp_plenum_roofs" => plenum_surfaces,
        "exp_nonplenum_roofs" => exposed_surfaces
    }

-geometry.rb in btap
Added 'make_convex_surfaces', 'get_overlapping_segments', 'subdivide_overlaps', 'line_segment_overlap_y?', and 'line_segment_x_coord'.  All of these essentially serve the 'make_convex_surfaces' method which takes a surface and creates convex surfaces out of it.  The input to 'make_convex_surfaces' is a flat OpenStudio horizontal surface whose normal points up.  If the z coordinates of the surface vertices are not all the same it returns an error.  It returns an array of surface hashes.  The surface hashes are flat, horizontal, convex quadrilaterals (or the odd triangle) whose normal points up (i.e. if you look down on the surface the vertices are in counter-clockwise order.  If surface passed to it is already a triangle or convex quadrilateral then the hash returned contains the original surface.  An array of hashes is returned instead of a new OpenStudio surface because I was worried that making new OpenStudio surfaces would mess up the model.  A new 'surf_centroid' method was also added to find the centroid of the surfaces created by 'make_convex_surfaces'

-Standards.SubSurface.rb in Standards:
Added 'sub_surface_create_centered_subsurface_from_scaled_surface' method which removes subsurfaces from a surface.  Then it creates a new window or skylight depending on if the surface is a wall or ceiling.  The new subsurface will have the same shape as the original surface only shrunk by a scaling factor towards the centroid of the surface.  This was originally written to put in new skylights.  However, although the method works it is not used because it only works for convex surfaces.  Some of the surfaces in the archetypes are concave.  To remedy this the 'sub_surface_create_scaled_subsurfaces_from_surface' method was added.  This method uses the 'make_convex_surfaces' method described above to turn a flat, horizontal, OpenStudio surface into an array of convex subsurfaces.  It then does what 'sub_surface_create_centered_subsurface_from_scaled_surface' does on each of the returned convex surfaces returned by 'make_convex_surfaces'.  Added 'set_Window_To_Wall_Ratio_set_name' method which uses the OpenStudio method 'setWindowToWallRatio' method but changes the name of the returned subsurface to whatever the name of the parent surface with the subsurface type added to the end (ex. a 'fxedwindow' type subsurface added to the 'mywall' surface would be called 'mywall_fixedwindow').  This was included to match the names of the subsurfaces generated by 'sub_surface_create_scaled_subsurfaces_from_surface' method.  Added the 'remove_All_Subsurfaces' method which was written to avoid having to create a loop every time I wanted to remove all of the subsurfaces from a surfaces.

-test_necb_constructions_fdwr.rb in test:
Fixed this unit test (which tests the fdwr and srr stuff I made above) so that it does not fail when the 'doors_average_conductance' returns an NA (the doors are all gone after the maximum fdwr is set) instead of a number.  I really should have fixed all the other return variables but was in a hurry and 'doors_average_conductance' was the only one that was failing.

Committed code to nrcan branch.  Issue now closed.
