### ISSUE TITLE
NECB 2015 Rules: Occupancy controls

### ISSUE THREAD

**Issue by khaddad** [canmet-energy/btap_tasks#15]
Spec writer: Mike
Implementation in BTAP: Jeff
Tester: Mike

Table 4.2.1.6. contains information on how the various lighting occupancy controls applicable to each space function. The first task in this ticket is to review all the lighting controls information in the previous table and section 4.2.2. to develop the rules for applying lighting occupancy controls in BTAP.

When lighting is deemed applicable for space, then the lighting power density for the space will be adjusted by an occupancy control factor and a personal control factor according to section 4.3.2.10.

The next step will be to implement the previous lighting rules in the BTAP NECB2015 class.

Quality assurance tasks:
New unit tests
All unit tests pass.
All regression tests pass

**Comment by edwardv720** [comment]
[NECB 2015 Occupancy Sensor for Lighting.docx](https://github.com/canmet-energy/btap_tasks/files/2068553/NECB.2015.Occupancy.Sensor.for.Lighting.docx)

Mike's spec

**Comment by edwardv720** [comment]
- Unsure how to retrieve the hourly occupancy schedule values from within standards

- 8.4.4.5 calls for the installed interior lighting power to be multiplied by the occupancy contrl and personal control factors. Isn't it simply adjusting the LPD once? i.e. regardless of occupancy schedule?

-Since the occupancy sensor factors applies if the occupancy schedule factor (0.0 to 1.0) is less than the relative absence factor (0.0 to 1.0), should an entirely new lighting schedule simply be made to include the factors, so the schedule adjusts the LPD?
