### ISSUE TITLE
Thermal Zoning of Archetypes to Better Reflect Geometry and Support Costing

### ISSUE THREAD

**Issue by mlubun** [canmet-energy/btap_tasks#157]
Some archetypes do thermal zoning floor by floor and it is very intuitive (small hotel for example is floor by floor).  Other archetypes do thermal zoning by specific space function and orientation and not floor by floor.  The large hotel is such an example.  It is a 6 storey building, but has 76 multipliers for certain suites.  Those multipliers represent suites on the same floor and across floors, but their exact positioning is unknown.  By not knowing how many of the 76 suites (or groups of suites) are located per floor it is unknown how to cost various energy end use components (service hot water piping, fan coil piping, ducting from rooftop AHU (Sys3).  A proposed solution would be to zone the large hotel and other archetypes that use multipliers for spaces amongst multiple floors on a floor by floor basis. The hospital is the current other archetype that uses multipliers across floors.  Other multi-storey archetypes such as office and murb use multipliers to multiplier the exact location of each thermal zone per floor and the zoning and multiplier combination is done is one direction only.

[large hotel zoning.docx](https://github.com/canmet-energy/btap_tasks/files/2394775/large.hotel.zoning.docx)

**Comment by phylroy** [comment]
Mike.. so the solution is to simply remove the sideway mulitpliers? Is that all?

**Comment by mlubun** [comment]
That is step 1.

Step 2 is the grouping of thermal zones under a single system, so if each floor of a hotel has a corridor, then there is a single system serving the corridor rather than a single system dedicated to each corridor thermal zone

**Comment by phylroy** [comment]
[spacetype_map.xlsx](https://github.com/canmet-energy/btap_tasks/files/2462065/spacetype_map.xlsx)
Here is @mlubun spacetype map..  There are two spacetypes in 2011 that are not in 2015.. 
*  Fire   station - engine room
*  Sports   arena - ring

What do you think they should map to in 2015?

**Comment by phylroy** [comment]
Stage one of this tasks in completed which was to map the spacetypes from NECB2011 -2015 automatically.  This required some spacetype changes to what @khaddad put in the models when he created them a few months back .  Also the space type colors are all white now.. no big deal I hope. 

Starting stage to which is a reexamination of the autozoning. 

```
Large Hotel
      "    \"A OS:SpaceType called 'Space Function Corridor/Transition area - hospital-sch-E' was found only in the true model\",",
      "    \"A OS:SpaceType called 'Space Function Storage room <= 5 m2 <= 100 m2-sch-E' was found only in the true model\",",
	  "    \"A OS:SpaceType called 'Space Function Corridor/Transition area other-sch-E' was found only in the compare model\",",
      "    \"A OS:SpaceType called 'Space Function Storage room < 5 m2-sch-A' was found only in the compare model\",",
      "    \"A OS:SpaceType called 'Space Function Storage room < 5 m2-sch-A 1' was found only in the compare model\",",


High Rise Apartment (old->new)
      "    \"A OS:SpaceType called 'Space Function Corridor/Transition area - hospital-sch-G' was found only in the true model\",",
      "    \"A OS:SpaceType called 'Space Function Office enclosed > 25 m2' was found only in the true model\",",
      "    \"A OS:SpaceType called 'Space Function Corridor/Transition area other-sch-G' was found only in the compare model\",",
      "    \"A OS:SpaceType called 'Space Function Office enclosed <= 25 m2' was found only in the compare model\",",

Hospital
 "    \"A OS:SpaceType called 'Space Function Office enclosed > 25 m2' was found only in the true model\",",
 "    \"A OS:SpaceType called 'Space Function Health care facility exam/treatment room' was found only in the compare model\",",
 "    \"A OS:SpaceType called 'Space Function Office enclosed <= 25 m2' was found only in the compare model\",",
 
 Midrise Apartment
       "    \"A OS:SpaceType called 'Space Function Corridor/Transition area - hospital-sch-G' was found only in the true model\",",
       "    \"A OS:SpaceType called 'Space Function Corridor/Transition area other-sch-G' was found only in the compare model\",",
 Outpatient
       "    \"A OS:SpaceType called 'Space Function Office enclosed > 25 m2' was found only in the true model\",",
       "    \"A OS:SpaceType called 'Space Function Storage room <= 5 m2 <= 100 m2-sch-H' was found only in the true model\",",
	   "    \"A OS:SpaceType called 'Space Function Laundry/Washing area' was found only in the compare model\",",
       "    \"A OS:SpaceType called 'Space Function Office enclosed <= 25 m2' was found only in the compare model\",",
       "    \"A OS:SpaceType called 'Space Function Storage room < 5 m2-sch-A' was found only in the compare model\",",
       "    \"A OS:SpaceType called 'Space Function Storage room < 5 m2-sch-A 1' was found only in the compare model\",",
 
 
Primary School
       "    \"A OS:SpaceType called 'Space Function Office enclosed > 25 m2' was found only in the true model\",",
       "    \"A OS:SpaceType called 'Space Function Office enclosed <= 25 m2' was found only in the compare model\",",
	   
Retail Stand Alone
		"    \"A OS:SpaceType called 'Space Function Storage room > 100 m2-sch-E' was found only in the true model\",",
		"    \"A OS:SpaceType called 'Space Function Storage room < 5 m2-sch-A' was found only in the compare model\",",
	   
Secondary School
		"    \"A OS:SpaceType called 'Space Function Office enclosed > 25 m2' was found only in the true model\",",
	   
Small Hotel
      "    \"A OS:SpaceType called 'Space Function Office enclosed > 25 m2' was found only in the true model\",",
      "    \"A OS:SpaceType called 'Space Function Storage room <= 5 m2 <= 100 m2-sch-F' was found only in the true model\",",

Small Office

      "    \"A OS:SpaceType called 'Space Function Office enclosed > 25 m2' was found only in the true model\",",
      "    \"A OS:SpaceType called 'Space Function Office enclosed <= 25 m2' was found only in the compare model\",",
Warehouse
      "    \"A OS:SpaceType called 'Space Function Office enclosed > 25 m2' was found only in the true model\",",
      "    \"A OS:SpaceType called 'Space Function Office enclosed <= 25 m2' was found only in the compare model\",",
```

**Comment by ckirney** [comment]
Issue #168 and #170 completed.  Now thermalzone multipliers are only used to multiply floors rather than zones within a floor.

**Comment by phylroy** [comment]
@ckirney @jblake59  @khaddad After reviewing the spec that @mlubun  wrote.. I am distilling it into simple logic that will be reviewed to by @mlubun .
 Zoning and System assignment will have to be done in stages since the initial sizing run may inform what system is used.  So we will perform Auto zoning first. 

## Auto-Zoning. 
### Dwelling units. 
1. Determine all the dwelling unit spaces in the model.  Use the"necb_hvac_system_selection_type" =   "Residential/Accomodation Area" to determine this. These are already defined in by spacetype in teh spacetypes.json file.  
2. Create a thermal zone. Name the Thermal zone "spacename+ZN"
3. Add the space to the thermal zone and the correct thermostat schedule. 
4. Set the system to ideal air/hvac for now. 

## WetSpaces
1. Modify the spacetypes.json file for 2011 and 2015 to have an identifier 'is_wet_space'
Wetspaces are
* Space Function “Locker room-sch-x” 
* Space Function “Washroom-sch-x” 

2. Merge similar loaded wet spaces into the same TZ per floor.  See how a similar loaded spacetype is defined below
3. All wet thermal zones will be served by a single sys4 in the whole buliding.. this will be done later after sizing. 

## Regular Spaces. 
0. Iterate though the spaces that are not wet and/or wild. 
1. Determine spaces that are of similarly load and group the spaces into the same TZ...  

## Wildcards that are not wetspaces. 
0. Iterate through all wildcard spaces that are not wet. 
1. Determine the adjacent spaces that are not dwelling units that have the most surface area in commom with the wildcard space and add that space to that adopting thermal zone adjusting the wild space schedule to be the same as the foster/parent spacetype. 
2. If there is no direct contact to a non-dwelling unit..space do not assign the space to anything and keep track of the skipped space. 
3. Once the first iteration of spaces have have been done. See if the skipped spaces are adjacent to any other wildcard spaces that were sucessfully assigned to a thermal zone.. if so, add the skipped space to the thermal zone adopting the tz schedule into the wildcard space. 
4. If after the second round there is still no thermal zone paring.. add this it's own thermal zone and keep track of these spaces so they are assign a system 4 system in the auto-system method later using the dominant floor schedule. 

## Similarly Loaded Spacetypes Definition.  
This means. 
   * Same envelope load ratio (surface-area/floor-area, direction, glazing, etc) 
   * Same space-type
   * Same multiplier number
   * Same floor

**Comment by phylroy** [comment]
[autozoner.zip](https://github.com/canmet-energy/btap_tasks/files/2664951/autozoner.zip)
@mlubun here are the files.. The JSON files contain the system->zone->space assignments.  Have a look at the most complex first.. If you find anything you don't like, stop testing and tell me. Thanks Mike!

**Comment by phylroy** [comment]
Conversation with @mlubun allowed for some new requirement. 
Zones with similar loads should be on the same airloop across floors.

**Comment by phylroy** [comment]
[autozoner.zip](https://github.com/canmet-energy/btap_tasks/files/2674261/autozoner.zip)
@mlubun  Here is a second stap that the autozone/system.  I have also added colors to the spacetypes to make it easier to discern them in sketchup spacetype views.

**Comment by phylroy** [comment]
@mlubun  requested these changes
Small Hotel: 4 stories with a front and rear storage space (with occupancy sensors) sys-4 in NECB 2011 Part 8.  8 total storage spaces but 2 rear storage zones were grouped into a single Sys-4 air loop while the rest had dedicated Sys-4 air loops.  Would prefer that all storage spaces be grouped into a single Sys-4 instead of multiple Sys-4.

Small Hotel: Elevator is correctly defined as a Lobby which would be a Sys 3, but a single  Sys 3 is defined for each floor, so there are 4 Sys 3 for the elevator.  Would prefer if they are grouped into a single Sys 3 if possible.  I realize that this may set a bad precedent because other Sys 3 assembly space functions (ie classrooms) are on multiple floors, then they could be grouped into a single Sys 3 also.  Could live with multiple Sys 3 for the elevator if a change causes more problems.

**Comment by phylroy** [comment]
To solve problem 2 it would be more appropriate that the elevators be set from lobby to corridor since it will provide lighting and heating loads for the space and force it to be a part of the wildcard spaces that assign a system 4 to it.  @mlubun to be consistent.. should all elevators in all models be set to this? To be consistent this should be applied to 

For problem 1.. Now all storage spaces will be on their own system 4 in the whole building.  Adding that to spec.
