### ISSUE TITLE
Space Cooling: Central Chiller Costing Spec

### ISSUE THREAD

**Issue by mlubun** [canmet-energy/btap_tasks#187]
Costing for chillers as well as associated pumps and piping. Note that this spec is very similar to boilers and cooling towers so updates/changes to one have been used in all three routines. This issue number used to hold branch for all these changes and updates.

**Comment by jblake59** [comment]
Mike's spec document.

[BTAP-Chiller Spec.docx](https://github.com/canmet-energy/btap_tasks/files/2718558/BTAP-Chiller.Spec.docx)

**Comment by jblake59** [comment]
Using this issue number for a branch (nrcan_187) that contains updated coding for this issue in addition to #182 (Boilers), #186 (Pumps) and #188 (cooling towers) because the approach and updated coding is very similar for all.

All of this coding is complete and has been tested against @mlubun hand calculations in Google Sheets. Tested for NECB2015 but also run successfully for 2011 and 2017.
