### ISSUE TITLE
NECB 2015 Rules: Schedules

### ISSUE THREAD

**Issue by khaddad** [canmet-energy/btap_tasks#8]
Information contained in Table C-A-8.4.3.2.1(A) through Table C-A-8.4.3.2.1(K) for the NECB 2015 operating schedules is in an Excel file we received from the NRC. New entries for the new NECB 2015 schedules need to be added to the BTAP data input environment in json. The new schedules should use NECB2015 in their name. Also the existing NECB schedules need to include NECB2011 in their names.

The BTAP NECB2011 and NECB2015 classes will be modified as needed to point to these schedules.

Quality assurance tasks: 
New unit tests for the NECB 2015 schedules
All unit tests pass
All regression tests pass

**Comment by ckirney** [comment]
Wrote NECB 2015 schedule json file.  Updated regression tests to match results from new NECB 2015 schedules.  Only schedules C and F changed.  Schedule C changed slightly, schedule F significantly.  Changes in regression tests were due to differences in schedules or as a result of those differences.  Only tests containing schedules C and F were affected.
